// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTsecLpO30stTY1kkoLtGc3PCZGZdcOF8',
    appId: '1:1073975519267:web:d76822be7531caed3da996',
    messagingSenderId: '1073975519267',
    projectId: 'emuexpensetracker',
    authDomain: 'emuexpensetracker.firebaseapp.com',
    storageBucket: 'emuexpensetracker.appspot.com',
    measurementId: 'G-8VJ55T1ZPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9RnYVSsHYv5It7skxeZQQKzbQePhpfjU',
    appId: '1:1073975519267:android:bc7570a472de0e453da996',
    messagingSenderId: '1073975519267',
    projectId: 'emuexpensetracker',
    storageBucket: 'emuexpensetracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtgVsyZ1Iep_5TYvv184aG3MCuH130FRg',
    appId: '1:1073975519267:ios:564af043e2ba0a8e3da996',
    messagingSenderId: '1073975519267',
    projectId: 'emuexpensetracker',
    storageBucket: 'emuexpensetracker.appspot.com',
    iosClientId: '1073975519267-jo5apd2bfhi4brothn7qfmqii29fb0rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.emu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtgVsyZ1Iep_5TYvv184aG3MCuH130FRg',
    appId: '1:1073975519267:ios:564af043e2ba0a8e3da996',
    messagingSenderId: '1073975519267',
    projectId: 'emuexpensetracker',
    storageBucket: 'emuexpensetracker.appspot.com',
    iosClientId: '1073975519267-jo5apd2bfhi4brothn7qfmqii29fb0rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.emu',
  );
}
